services:
  postgres:
    image: postgres:18.1
    container_name: barbershop_postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      TZ: UTC
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - barbershop_pgdata:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: barbershop_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - barbershop_pgadmin_data:/var/lib/pgadmin

volumes:
  barbershop_pgdata:
    name: barbershop_pgdata
  barbershop_pgadmin_data:
    name: barbershop_pgadmin_data
